channels:
  - conda-forge
dependencies:
  - python==3.9
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - matplotlib==3.5.1
  - numpy==1.21.2
  - pandas==1.4.1
  - plotly==5.7.0
  - chart-studio==1.1.0
  - scipy==1.7.3
  - pip:
    - nbsphinx